### ISSUE TITLE
Look into automatically exposing components

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#122] opened 2018-07-31 19:14 UTC
Currently, components are manually exposed.  We should look into how we might automate this so that components don't get forgotten about and more difficult to access.

**Comment by stephenp** [comment] 2018-07-31 19:15
Dupe of https://github.com/yankaindustries/mc-components/issues/121, you're too slow, dude. :P

**Closed by stephenp** 2018-07-31 19:15 UTC
Labels: enhancement
